config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :movies

  root to: "lists#index"
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
  resources :bookmarks, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, presence: true, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :bookmarks
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  has_many :bookmarks
  has_many :lists, through: :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def index
    @bookmarks = Bookmark.all
  end

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    @bookmark.save
    redirect_to list_path(@list)
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @bookmark = Bookmark.find(params[:id])
    @bookmark.update(bookmark_params)
    redirect_to @bookmark.list
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(lists_params)
    @list.save
    redirect_to lists_path
  end




  private

  def lists_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/edit.html.erb
<div class="form-input">
    <%= simple_form_for @bookmark do |f| %>
        <%= f.input :comment, html5: true, label: "Comment" %>
        <%= f.submit "Update", class:"btn btn-primary" %>
    <% end %>
  </div>

app/views/bookmarks/new.html.erb
<%= link_to "retour", lists_path, class:"btn btn-primary" %>

<h3>Add a movie to your <%= @list.name %> list</h3>
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
          <%= f.association :movie, prompt: "Select a movie", input_html: {data: { controller: "tom-select"}} %>
          <%= f.submit class: "btn btn-flat" %>
        <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WatchListTraining</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<%= link_to "add a new list", new_list_path, class:"btn btn-primary" %>
<h1>Lists 📖</h1>
  <% @lists.each do |list| %>
    <%= link_to list_path(list) do %>
    <%= list.name %>
    <% end %>
  <% end %>

app/views/lists/new.html.erb
<%= link_to "retour", lists_path, class:"btn btn-primary" %>

<div class="form">
  <div class="title-form" >
    <h1>Your new list 🚩</h1>
  </div>
  <div class="form-input">
    <%= simple_form_for @list do |f| %>
        <%= f.input :name, html5: true, label: "Name" %>
        <%= f.submit "Create", class:"btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
<%= link_to "retour", lists_path, class:"btn btn-primary" %>
<h1>More details about your lists</h1>
  <%= @list.name %>
  <% @bookmarks.each do |bookmark|%>
    <%= link_to "delete", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "are you sure"}%>
    <%= link_to "edit", edit_bookmark_path(bookmark) %>
    <%= bookmark.movie.title %>
    <%= bookmark.movie.description%>
    <%= bookmark.comment %>
  <% end %>
  <%= link_to "add a new bookmark", new_list_bookmark_path(@list) %>